#ifndef MLP_AUXILIARY_MODULES_TRAINING_PARAMETERS_H_
#define MLP_AUXILIARY_MODULES_TRAINING_PARAMETERS_H_


struct TrainingParameters {

    

};  // TrainingParameters


#endif  // MLP_AUXILIARY_MODULES_TRAINING_PARAMETERS_H_
